[tox]
envlist = py38, py311
isolated_build = true

[testenv]
extras = dev
commands =
    pytest {posargs:tests/unit}

[testenv:integration]
extras = dev
commands =
    pytest {posargs:tests/integration}
